services:
  - type: web
    name: telegram-bruteforce-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    sartCommand: python bot.py
    autoDeploy: true
